/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const AWSConfig = {
  "aws_project_region": "eu-west-1",
  "aws_cognito_identity_pool_id": "eu-west-1:162bddd0-e3bf-44ec-a224-828cf7362614",
  "aws_cognito_region": "eu-west-1",
  "aws_user_pools_id": "eu-west-1_EHOma2t5P",
  "aws_user_pools_web_client_id": "78j55n1dp5inbfl67k2p6ogkv7",
  "oauth": {},
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ],
  "aws_user_files_s3_bucket": "gendac-cvs80138-dev",
  "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default AWSConfig;
