/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const AWSConfig = {
  "aws_project_region": "eu-west-1",
  "aws_cognito_identity_pool_id": "eu-west-1:d4cc4bc0-aa90-4e53-9707-61fe6da43b65",
  "aws_cognito_region": "eu-west-1",
  "aws_user_pools_id": "eu-west-1_T1EmwjFvy",
  "aws_user_pools_web_client_id": "2nlk3kg7jr0b33hqpctvhqev4q",
  "oauth": {},
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ],
  "aws_user_files_s3_bucket": "gendac-cvs80138-dev",
  "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default AWSConfig;
